#!/usr/bin/env python

import os
import sys
import boto.ec2
import time
import subprocess
import glob

# =========== settings =====================

REGION = "us-east-1"
AMI = "ami-a29943cb" # precise 64 east ebs http://cloud.ubuntu.com/ami/
INSTANCE_TYPE = "m1.large"
MACHINENAME = "studio"
ELASTIC_IP = "184.73.165.116"
HOSTNAME_OF_IP = "studio.declinefm.com"
INITIAL_SSH_KEYS = """ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCgrwFxvP8S5wlG+rcoWTyfJN6526BYFASt1Xgs1nFuA8/NFjUyQiSX1IvnWTupwS+2zveFncAMLTUPED+6qIOFmhzYIEfFEcTlap+8RKU9Cydbbhv5GChoN4dcbysRJ8g6vfye1SqVE/iHcglYRQHpXgGsP9vuv5vpIVGH39l7Pssd7lAVjbFJ/tmEtyk7BNWi6sgZVEV7McsA9D/qqtoXlAJ6Hm+O4R00UQkJZhdmZUBp+zKLrvIl3IvYGkvGj+p/7bh1+3XHqEhmtxb/Pdv3ziYNKPOUKIBGUBa7uAA+g3pWl5/0oTUX2UWHC8URij6i4cd3ckLVQOF5k6DjumbR nevermaker@gmail.com
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDEmisawhXKPmU7WBXlq6NhSWfqwVg5MiEOIZxLEcG1T7tjsCrW8V8zOHi8dI5jXeiIF2np12ahTZOHE/s1u2bLXIosjczt+R1FDthFZ9L3m6OhVCqLviAO5avkpW8oErqpjLKnX3yS8emYQNaOC6O2z+/dnN9DsUh9fueNnpheJClwXsdEJ0LXfOOay1MrS/O/DtKjkPfC212rnwwoj+DMZWN6vExyVXPipuG6QkVc9Wpr7WWVNeFM/mWSUBgItW7ipVemTveObz87lcTwPwUbMnauyUNmpyHsEtlcUesm8lxnQ0+KtZFuLxt6UgP3fR/tBaKr59F1SwVmurYpIDZl user@ring2-projects
"""

# ========== set up the machine ============

SETUP_SCRIPT = """#!/bin/bash -x
exec &>> /var/log/cloud-init.log
set -x
homedir=/home/ubuntu
# set up ssh key
echo "%s" >> $homedir/.ssh/authorized_keys
""" % (INITIAL_SSH_KEYS)

conn = boto.ec2.connect_to_region(REGION)

if len(sys.argv) > 1:
	instance_id = sys.argv[1]

else:
	machinesnamedstudio = conn.get_all_instances(filters={"tag:Name":MACHINENAME})
	if machinesnamedstudio:
		instance_id = machinesnamedstudio[0].instances[0].id
	else:
		resv = conn.run_instances(
			AMI,
			instance_type=INSTANCE_TYPE,
			user_data=SETUP_SCRIPT,
		)
		instance_id = resv.instances[0].id
		conn.create_tags([instance_id], {'Name': MACHINENAME})

i = conn.get_all_instances([instance_id])[0].instances[0]
while True:
	i.update()
	print i.id, i.state, i.instance_type, i.ip_address
	if i.state == "stopped":
		i.start()
		time.sleep(5)
		continue
	if i.state == "running": break
	time.sleep(5)

conn.associate_address(instance_id, ELASTIC_IP)

f = file(os.path.expanduser("~/.studiohosts"), "w")
f.write(HOSTNAME_OF_IP)
f.flush()
f.close()

print "Now you are ready to log into the instance"
print "and to set it up using ansible"
print "IP address: %s"%ELASTIC_IP
print "Refer to the README for ansible information"

