#!/bin/bash

set -e

[ -f "$1" ] || { echo usage: encodetomp3 filename [num] [yyyy-mm-dd] [aftershow?] ; exit 64 ; }

[ -n "$STUDIOARCHIVEDIR" ]   || export STUDIOARCHIVEDIR=~/Documents/Studio\ archive
[ -n "$SHOWNUMBERREGEXP" ]   || export SHOWNUMBERREGEXP="Decline to State show (\d+)"
[ -n "$SHOWTITLEPREFIX" ]    || export SHOWTITLEPREFIX="Show #"
[ -n "$SHOWFILENAMEPREFIX" ] || export SHOWFILENAMEPREFIX="Decline to State show "
[ -n "$SHOWSOURCEURL" ]      || export SHOWSOURCEURL="http://declinefm.com/archives"

export AFTERSHOW=0
if [ -n "$4" ] ; then export AFTERSHOW=1 ; fi

shortdate=`date "+%Y-%m-%d"`
if [ -n "$3" ] ; then shortdate="$3" ; fi

enddir="$STUDIOARCHIVEDIR"/"$shortdate"

if [ -n "$2" ] ; then
    shownum="$2"
    if [ "$AFTERSHOW" == "1" ] ; then
        shownum=`echo -n "$shownum" | python -c 'import sys; print "%06.1f"%float(sys.stdin.read())'`
    else
        shownum=`echo -n "$shownum" | python -c 'import sys; print "%04d"%int(sys.stdin.read())'`
    fi
else
    shownum=`python -c 'import urllib2, urllib
import xml.dom.minidom as dom
import os.path
import re

showurl = os.environ["SHOWSOURCEURL"]
shownumberexp = os.environ["SHOWNUMBERREGEXP"]
aftershow = os.environ["AFTERSHOW"]

req = urllib2.urlopen(showurl)
data = req.read()
domtree = dom.parseString(data)
urls = [ a.getAttribute("href") for a in domtree.getElementsByTagName("a") ]
urls = [ urllib.unquote(u) for u in urls ]
matches = [ int(re.findall(shownumberexp,u)[0]) for u in urls if re.findall(shownumberexp,u) ]
highest = max(matches)
next = highest + 1
if aftershow == "0":
    print "%04d"%next
elif aftershow == "1":
    next = highest + 0.1
    print "%06.1f"%next
else: assert 0
'`
fi

if [ "$AFTERSHOW" == "1" ] ; then
    showshortnum=`python -c "print float('$shownum')"`
else
    showshortnum=`python -c "print int('$shownum')"`
fi

longdate=`echo -n "$shortdate" | python -c 'import sys, time; print time.strftime("%B %d %Y",time.strptime(sys.stdin.read(), "%Y-%m-%d"))'`
year=`echo -n "$shortdate" | python -c 'import sys, time; print time.strftime("%Y",time.strptime(sys.stdin.read(), "%Y-%m-%d"))'`

if [ "$AFTERSHOW" == "1" ] ; then
    filenametoupload="$enddir"/"$SHOWFILENAMEPREFIX""$shownum Aftershow for $longdate.mp3"
    showtitle="$SHOWTITLEPREFIX""$showshortnum: Aftershow for $longdate"
else
    filenametoupload="$enddir"/"$SHOWFILENAMEPREFIX""$shownum $longdate.mp3"
    showtitle="$SHOWTITLEPREFIX""$showshortnum: $longdate"
fi

mkdir -p "$enddir"

if [ ! -f "$filenametoupload" ] ; then
lame --replaygain-accurate -q0 -b 96 "$1" "$filenametoupload"
fi

id3tag -a"The Decline to State team" -s"$showtitle" -y$year "$filenametoupload"

echo
echo "Preparation done.  Parameters for upload:"
echo Show file name: `basename "$filenametoupload"`
echo Show title: "$showtitle"
